import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Hello world ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` bg-gray-100 text-black/80`}>
        <Navbar />
        <main className="max-w-4xl mx-auto p-8">{children}</main>
      </body>
    </html>
  );
}

// npx vs npm
